# Generated by Django 2.0.5 on 2018-05-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='destiny',
            field=models.CharField(choices=[('Brasil', 'Peru'), ('Argentina', 'Chile')], max_length=1),
        ),
    ]
